all infra added

diff --git a/.github/workflows/static-analysis.yaml b/.github/workflows/static-analysis.yaml
--- a/.github/workflows/static-analysis.yaml
+++ b/.github/workflows/static-analysis.yaml
@@ -11,9 +11,28 @@ permissions:
 
 jobs:
   # Secret scanning job: Scans the repository for any secrets.
+
+  check-tf-location:
+    runs-on: ubuntu-latest
+    name: Check Terraform files location
+    steps:
+      - name: Checkout source code
+        uses: actions/checkout@v4  # Checkout the repository code.
+
+      - name: Ensure all .tf files are under the infra folder
+        run: |
+          if git ls-files '*.tf' | grep -v '^infra/'; then
+            echo "ERROR: Found .tf files outside of the infra/ folder!"
+            exit 1  # Fail the pipeline if any .tf files are outside infra/
+          else
+            echo "All .tf files are under the infra/ folder."
+          fi
+
+
   secret-scan:
     name: "Secret Scan"
     runs-on: ubuntu-latest
+    needs: check-tf-location
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
